// frama-c -eva -kernel-warn-key CERT:MSC:38=inactive -main f FunctionCall.c -slice-pragma f -slicing-level=2 -then-on 'Slicing export' -print > tmp.c
[kernel] Parsing FunctionCall.c (with preprocessing)
[eva] Analyzing a complete application starting at f
[eva:initial-state] Values of globals at initialization
  
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function getValue:
  __retres ∈ {42}
[eva:final-states] Values at end of function f:
  i ∈ {43}
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  2 functions analyzed (out of 3): 66% coverage.
  In these functions, 6 statements reached (out of 6): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
[slicing] slicing requests in progress...
[slicing] initializing slicing ...
[slicing] interpreting slicing requests from the command line...
[pdg] computing for function f
[from] Computing for function getValue
[from] Done for function getValue
[pdg] done for function f
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[slicing] applying all slicing requests...
[slicing] applying 1 actions...
[slicing] applying actions: 1/1...
[pdg] computing for function getValue
[pdg] done for function getValue
[slicing] exporting project to 'Slicing export'...
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[sparecode] remove unused global declarations from project 'Slicing export tmp'
[sparecode] removed unused global declarations in new project 'Slicing export'
/* Generated by Frama-C */
int getValue_slice_1(void)
{
  int __retres;
  __retres = 42;
  return __retres;
}

void f(void)
{
  int i;
  i = getValue_slice_1();
  /*@ slice pragma expr i; */ ;
  return;
}


