// frama-c -eva -kernel-warn-key CERT:MSC:38=inactive -main main PointerArithmetic.c -slice-pragma main -slicing-level=2 -then-on 'Slicing export' -print > tmp.c
[kernel] Parsing PointerArithmetic.c (with preprocessing)
[eva] Analyzing a complete application starting at main
[eva:initial-state] Values of globals at initialization
  
[eva] PointerArithmetic.c:7: starting to merge loop iterations
[eva:alarm] PointerArithmetic.c:12: Warning: 
  accessing uninitialized left-value. assert \initialized(elementPointer);
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function main:
  values[0] ∈ {1; 2; 3} or UNINITIALIZED
        [1] ∈ {1; 2; 3}
        [2] ∈ {1; 2; 3} or UNINITIALIZED
  i ∈ {3}
  elementPointer ∈ {{ &values[1] }}
  element ∈ {2; 3; 4}
  __retres ∈ {0}
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 1): 100% coverage.
  In this function, 13 statements reached (out of 13): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  1 alarm generated by the analysis:
       1 access to uninitialized left-values
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
[slicing] slicing requests in progress...
[slicing] initializing slicing ...
[slicing] interpreting slicing requests from the command line...
[pdg] computing for function main
[pdg] done for function main
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[slicing] applying all slicing requests...
[slicing] applying 1 actions...
[slicing] applying actions: 1/1...
[slicing] exporting project to 'Slicing export'...
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[sparecode] remove unused global declarations from project 'Slicing export tmp'
[sparecode] removed unused global declarations in new project 'Slicing export'
/* Generated by Frama-C */
void main(void)
{
  int values[3];
  int i;
  int *elementPointer;
  int element;
  i = 0;
  while (i < 3) {
    values[i] = i + 1;
    i ++;
  }
  elementPointer = & values[1];
  element = *elementPointer;
  /*@ slice pragma expr element; */ ;
  return;
}


