// frama-c -eva -kernel-warn-key CERT:MSC:38=inactive -main foo UnfeasiblePath.c -slice-pragma foo -slicing-level=2 -then-on 'Slicing export' -print > tmp.c
[kernel] Parsing UnfeasiblePath.c (with preprocessing)
[kernel:CERT:MSC:37] UnfeasiblePath.c:11: Warning: 
  Body of function foo falls-through. Adding a return statement
[eva] Analyzing a complete application starting at foo
[eva:initial-state] Values of globals at initialization
  
[eva:alarm] UnfeasiblePath.c:11: Warning: 
  assertion 'missing_return' got status invalid (stopping propagation).
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function foo:
  NON TERMINATING FUNCTION
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 2): 50% coverage.
  In this function, 7 statements reached (out of 9): 77% coverage.
  ----------------------------------------------------------------------------
  Some errors and warnings have been raised during the analysis:
    by the Eva analyzer:      0 errors    0 warnings
    by the Frama-C kernel:    0 errors    1 warning
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  Evaluation of the logical properties reached by the analysis:
    Assertions        0 valid     0 unknown     1 invalid      1 total
    Preconditions     0 valid     0 unknown     0 invalid      0 total
  0% of the logical properties reached have been proven.
  ----------------------------------------------------------------------------
[slicing] slicing requests in progress...
[slicing] initializing slicing ...
[slicing] interpreting slicing requests from the command line...
[pdg] computing for function foo
[pdg] UnfeasiblePath.c:11: Warning: no final state. Probably unreachable...
[pdg] done for function foo
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[slicing] applying all slicing requests...
[slicing] applying 1 actions...
[slicing] applying actions: 1/1...
[slicing] exporting project to 'Slicing export'...
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[sparecode] remove unused global declarations from project 'Slicing export tmp'
[sparecode] removed unused global declarations in new project 'Slicing export'
/* Generated by Frama-C */
void foo(int cond)
{
  int value;
  value = 0;
  value ++;
  if (! cond) 
    /*@ slice pragma expr value; */ ;
  /*@ assert missing_return: \false; */ ;
  return;
}


