// frama-c -eva -kernel-warn-key CERT:MSC:38=inactive -main foo LoopBreak.c -slice-pragma foo -slicing-level=2 -then-on 'Slicing export' -print > tmp.c
[kernel] Parsing LoopBreak.c (with preprocessing)
[eva] Analyzing a complete application starting at foo
[eva:initial-state] Values of globals at initialization
  
[eva] LoopBreak.c:3: starting to merge loop iterations
[eva] ====== VALUES COMPUTED ======
[eva:final-states] Values at end of function foo:
  i ∈ {42; 43}
[eva:summary] ====== ANALYSIS SUMMARY ======
  ----------------------------------------------------------------------------
  1 function analyzed (out of 2): 50% coverage.
  In this function, 13 statements reached (out of 13): 100% coverage.
  ----------------------------------------------------------------------------
  No errors or warnings raised during the analysis.
  ----------------------------------------------------------------------------
  0 alarms generated by the analysis.
  ----------------------------------------------------------------------------
  No logical properties have been reached by the analysis.
  ----------------------------------------------------------------------------
[slicing] slicing requests in progress...
[slicing] initializing slicing ...
[slicing] interpreting slicing requests from the command line...
[pdg] computing for function foo
[pdg] done for function foo
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[slicing] applying all slicing requests...
[slicing] applying 1 actions...
[slicing] applying actions: 1/1...
[slicing] exporting project to 'Slicing export'...
[slicing] applying all slicing requests...
[slicing] applying 0 actions...
[sparecode] remove unused global declarations from project 'Slicing export tmp'
[sparecode] removed unused global declarations in new project 'Slicing export'
/* Generated by Frama-C */
void foo(int b)
{
  int i = 0;
  while (i < 42) {
    if (b % 2 == 0) i += 2;
    else {
      /*@ slice pragma expr i; */ ;
      i ++;
    }
    if (i == 21) break;
  }
  return;
}


